set "INCLUDE=%INCLUDE%;%LIBRARY_INC%\OpenEXR;%LIBRARY_INC%\Imath"
set "CXXFLAGS=%CXXFLAGS% /bigobj"
set "CMAKE_ARGS=%CMAKE_ARGS% -DOPENEXR_FORCE_INTERNAL_DEFLATE=OFF -DOPENEXR_FORCE_INTERNAL_IMATH=OFF -DOPENEXR_FORCE_INTERNAL_OPENJPH=OFF -DOPENEXR_FORCE_INTERNAL_ZSTD=OFF"
%PYTHON% -m pip install . -vv
if errorlevel 1 exit 1
