{% set name = "OpenEXR" %}
{% set version = "1.3.9" %}

package:
  name: openexr-python  # clash with existing openexr C++ library
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/OpenEXR-{{ version }}.tar.gz
  sha256: cffcd13906291ef1a81b369c1c0e907648ecd24363668873691f44866704ab21
  patches:
    - exr3-linkage.patch
    - windows-fix.patch  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - openexr
    - pip
    - python
    - zlib
  run:
    - openexr
    - python

test:
  imports:
    - Imath
    - OpenEXR
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.excamera.com/sphinx/articles-openexr.html
  summary: Python bindings for ILM's OpenEXR image file format
  license: BSD-3-Clause
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE

extra:
  recipe-maintainers:
    - pkgw
