{% set name = "OpenEXR" %}
{% set version = "1.3.5" %}

package:
  name: openexr-python  # clash with existing openexr C++ library
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/OpenEXR-{{ version }}.tar.gz
  sha256: 32fa26b9c860d2a352bdc803dabc0378482d2e6cfd986a49734b3171cf01aad0
  patches:
    - windows-fix.patch  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - ilmbase
    - openexr
    - pip
    - python
  run:
    - ilmbase
    - openexr
    - python

test:
  imports:
    - Imath
    - OpenEXR
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.excamera.com/sphinx/articles-openexr.html
  summary: Python bindings for ILM's OpenEXR image file format
  license: BSD-3-Clause
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE

extra:
  recipe-maintainers:
    - pkgw
