# Note: if you're updating this recipe for a new upstream release, make sure
# that the value of c_stdlib_version (MACOSX_DEPLOYMENT_TARGET) in
# `conda_build_config.yaml` stays synchronized with what upstream has in its
# `pyproject.toml` scikit-build configuration.

{% set name = "OpenEXR" %}
{% set version = "3.4.0" %}

package:
  name: openexr-python  # clash with existing openexr C++ library
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 022d059e089ddf6c5fcc3085c65418be52c6d871317d72e04f4228ea11fe65eb

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake
    - make
  host:
    - openexr
    - pip
    - pybind11
    - python
    - scikit-build-core
    - zlib
  run:
    - numpy
    - openexr
    - python

test:
  imports:
    - Imath
    - OpenEXR
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.excamera.com/sphinx/articles-openexr.html
  summary: Python bindings for ILM's OpenEXR image file format
  license: BSD-3-Clause
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE

extra:
  recipe-maintainers:
    - pkgw
