{% set name = "OpenEXR" %}
{% set version = "3.3.2" %}

package:
  name: openexr-python  # clash with existing openexr C++ library
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 150e1b8f817ce351087c041e8d19f18ab7e799a8dbe099faa5b611ce6688f246
  patches:
    - exr3-linkage.patch
    - windows-fix.patch  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - openexr
    - pip
    - python
    - setuptools
    - zlib
  run:
    - openexr
    - python

test:
  imports:
    - Imath
    - OpenEXR
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.excamera.com/sphinx/articles-openexr.html
  summary: Python bindings for ILM's OpenEXR image file format
  license: BSD-3-Clause
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE

extra:
  recipe-maintainers:
    - pkgw
