# Note: if you're updating this recipe for a new upstream release, make sure
# that the value of c_stdlib_version (MACOSX_DEPLOYMENT_TARGET) in
# `conda_build_config.yaml` stays synchronized with what upstream has in its
# `pyproject.toml` scikit-build configuration.

# Also note: due to the way the software is packaged, these Python bindings
# cannot reuse the shared library provided by the `openexr` package, as far as I
# can tell. So this package is actually independent of that one, but builds a
# lot of the same C++ code.

{% set name = "OpenEXR" %}
{% set version = "3.4.5" %}

package:
  name: openexr-python  # distinguish from the `openexr` C++ library package
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 74ade27b73789f24d0f35d6095a27771de01fea47a30980f2d98613cb5e3cec9

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake
    - make
  host:
    - imath
    - libdeflate
    - openjph
    - pip
    - pybind11
    - python
    - scikit-build-core
    - zlib
  run:
    - numpy
    - python

test:
  imports:
    - Imath
    - OpenEXR
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.excamera.com/sphinx/articles-openexr.html
  summary: Python bindings for ILM's OpenEXR image file format
  license: BSD-3-Clause
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE

extra:
  recipe-maintainers:
    - pkgw
