# Note: make sure that the value of c_stdlib_version (MACOSX_DEPLOYMENT_TARGET)
# in `conda_build_config.yaml` stays synchronized with `macos-platform.patch`
# and/or what upstream expects in the scikit-build config in its
# `pyproject.toml` file.
#
# Also note: due to the way the software is packaged, these Python bindings
# cannot reuse the shared library provided by the `openexr` package, as far as I
# can tell. So this package is actually independent of that one, but builds a
# lot of the same C++ code.

schema_version: 1

context:
  name: OpenEXR
  version: "3.5.1"

package:
  name: openexr-python  # distinguish from the `openexr` C++ library package
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/${{ name|lower }}-${{ version }}.tar.gz
  sha256: e48d64bc8388ed18eff2f76007034ee3d48f276dbbac08e6c66389a3bb3e9ec7
  patches:
    - if: osx
      then: macos-platform.patch

build:
  number: 0

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake
    - make
    - pkg-config
  host:
    - imath
    - libdeflate
    - openjph >=0.32.0
    - pip
    - pybind11
    - python
    - scikit-build-core <1.0  # upstream not compatible as of 3.4.13 (2026 Aug); can probably relax this soon
    - zlib
    - zstd
  run:
    - numpy
    - python

tests:
  - python:
      imports:
        - Imath
        - OpenEXR
      pip_check: true

about:
  summary: Python bindings for ILM's OpenEXR image file format
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: http://www.excamera.com/sphinx/articles-openexr.html

extra:
  recipe-maintainers:
    - pkgw
